// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: lulu2_menu

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
void ui_event_ButtonMenu( lv_event_t * e);
lv_obj_t *ui_ButtonMenu;
void ui_event_thredotsLabel( lv_event_t * e);
lv_obj_t *ui_thredotsLabel;
lv_obj_t *ui_ButtonSleep;
lv_obj_t *ui_ButtonBack;
lv_obj_t *ui_Container1;
lv_obj_t *ui_ButtonAction1;
lv_obj_t *ui_ButtonAction2;
lv_obj_t *ui_ButtonAction3;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
void ui_event_BtnBack( lv_event_t * e);
lv_obj_t *ui_BtnBack;
lv_obj_t *ui_Container3;
lv_obj_t *ui_BtnScripts;
lv_obj_t *ui_Scripts;
lv_obj_t *ui_BtnShortcuts;
lv_obj_t *ui_ShortcutsLabel;
lv_obj_t *ui_BtnSound;
lv_obj_t *ui_LabelSound;
lv_obj_t *ui_BtnWiFi;
lv_obj_t *ui_LabelWiFi;
lv_obj_t *ui_BtnMoves;
lv_obj_t *ui_LabelMoves;
lv_obj_t *ui_SwitchWiFi;
lv_obj_t *ui_SwitchAudio;
lv_obj_t *ui_SwitchMove;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_back[1] = {&ui_img_back48_png};
const lv_img_dsc_t *ui_imgset_d[3] = {&ui_img_d1_png, &ui_img_d2_png, &ui_img_d4_png};
const lv_img_dsc_t *ui_imgset_sleep_dog_[1] = {&ui_img_sleep_dog_100_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonMenu( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
}
}

void ui_event_thredotsLabel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
}
}

void ui_event_BtnBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
