// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: lulu2_menu

#include "ui.h"

void my_func(lv_event_t * e)
{
	// Your code here
}
