// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: lulu2_menu

#include "ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller3 = lv_roller_create(ui_Screen3);
lv_roller_set_options( ui_Roller3, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_Roller3, 200);
lv_obj_set_height( ui_Roller3, 200);
lv_obj_set_x( ui_Roller3, 2 );
lv_obj_set_y( ui_Roller3, -4 );
lv_obj_set_align( ui_Roller3, LV_ALIGN_CENTER );

ui_Button12 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button12, 90);
lv_obj_set_height( ui_Button12, 78);
lv_obj_set_x( ui_Button12, -93 );
lv_obj_set_y( ui_Button12, -80 );
lv_obj_set_align( ui_Button12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button12, 55, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button12, &ui_img_back48_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0x636363), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Button12, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Button12, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Button12, 2, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);

}
