#define COMMAND_SET_TAIL_SPEED 0
#define COMMAND_STAND 1
#define COMMAND_SIT 2
#define COMMAND_LAYDOWN 3
#define COMMAND_HAPPY 4
#define COMMAND_LEFTHAND 5
#define COMMAND_HALFLAYDOWN 6
#define COMMAND_DANCE1 7
#define COMMAND_RIGHTHAND 8
#define COMMAND_FULLLAYDOWN 9
#define COMMAND_TAILLEGSSTAND 10
#define COMMAND_HALFLAYDOWNTAIL 11


#define RP_SYS_COMMAND_SLEEP 201
#define RP_SYS_COMMAND_WAKE 200
#define RP_SYS_COMMAND_PING 211